# Generated by Django 6.0.7 on 2026-07-12 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0001_initial'),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='The Pulse', max_length=100)),
                ('logo_light', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('logo_dark', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('primary_color', models.CharField(default='#2F6DF6', max_length=7)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('footer_text', models.TextField(blank=True, default='© 2026 The Pulse. Futuristic Digital Journalism.')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='HomepageLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('hero', 'Hero Lead Story Section'), ('featured-grid', 'Secondary Featured Grid (3-4 stories)'), ('category-rail', 'Category Scroll Rail'), ('ad-slot', 'Advertisement Banner Block'), ('trending-widget', 'Trending & Popular List Sidebar')], max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('ad_slot', models.ForeignKey(blank=True, help_text='Required for Advertisement Banner Block sections', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads.adslot')),
                ('category', models.ForeignKey(blank=True, help_text='Required for Category Scroll Rail sections', null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.category')),
            ],
            options={
                'verbose_name': 'Homepage Layout Section',
                'verbose_name_plural': 'Homepage Layout Sections',
                'ordering': ['order'],
            },
        ),
    ]
