# Generated by Django 6.0.7 on 2026-07-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyVerse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date for which this verse is shown', unique=True)),
                ('verse_reference', models.CharField(help_text='e.g., Yohana 3:16 / John 3:16', max_length=255)),
                ('verse_text_kinyarwanda', models.TextField(help_text='Verse text in Kinyarwanda')),
                ('verse_text_english', models.TextField(help_text='Verse text in English')),
            ],
            options={
                'verbose_name': 'Daily Verse',
                'verbose_name_plural': 'Daily Verses',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='footer_text',
            field=models.TextField(blank=True, default='© 2026 Isezerano. Futuristic Digital Journalism.'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_name',
            field=models.CharField(default='Isezerano', max_length=100),
        ),
    ]
