# Generated by Django 6.0.7 on 2026-07-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0002_dailyverse_alter_sitesetting_footer_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='footer_recent_limit',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='homepage_limit',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
