# Generated by Django 6.0.7 on 2026-07-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0003_sitesetting_footer_recent_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagelayout',
            name='article_limit',
            field=models.PositiveIntegerField(default=5, help_text='Number of articles to fetch for this section'),
        ),
        migrations.AlterField(
            model_name='homepagelayout',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero Lead Story Section'), ('featured-grid', 'Secondary Featured Grid (3-4 stories)'), ('category-rail', 'Category Scroll Rail'), ('ad-slot', 'Advertisement Banner Block'), ('trending-widget', 'Trending & Popular List Sidebar'), ('news-desk', 'News Desk Section'), ('announcements', 'Amatangazo Classifieds Section'), ('lifestyle', 'Lifestyle & Culture Section'), ('sports-grid', 'Sports Vertical Grid Section'), ('featured-secondary', 'Second Featured Posts Row'), ('flyers', 'Local Partner Flyers Row'), ('you-missed', 'You Missed Scroll Rail')], max_length=30),
        ),
    ]
