# Generated by Django 6.0.7 on 2026-08-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0005_dailyverse_verse_text_french'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter/X'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn'), ('custom', 'Custom Platform')], default='custom', max_length=20)),
                ('custom_name', models.CharField(blank=True, help_text='Required for custom platform', max_length=50)),
                ('url', models.URLField()),
                ('icon_name', models.CharField(default='link', help_text='Lucide icon name (e.g. facebook, twitter, instagram, link)', max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='homepagelayout',
            options={'ordering': ['order'], 'verbose_name': 'Page Section', 'verbose_name_plural': 'Page Sections'},
        ),
        migrations.AddField(
            model_name='homepagelayout',
            name='content',
            field=models.TextField(blank=True, help_text='HTML/markdown content for text sections'),
        ),
        migrations.AddField(
            model_name='homepagelayout',
            name='page',
            field=models.CharField(db_index=True, default='home', max_length=50),
        ),
        migrations.AddField(
            model_name='homepagelayout',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='active_theme',
            field=models.CharField(default='theme-classic', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='bg_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='btn_bg_color',
            field=models.CharField(default='#062360', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='btn_text_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='custom_css',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='font_color',
            field=models.CharField(default='#0F1117', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='font_family_body',
            field=models.CharField(default='Inter', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='font_family_headings',
            field=models.CharField(default='Playfair Display', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hover_color',
            field=models.CharField(default='#0A3490', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='link_color',
            field=models.CharField(default='#062360', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='secondary_color',
            field=models.CharField(default='#F0F4FF', max_length=7),
        ),
        migrations.AlterField(
            model_name='homepagelayout',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero Lead Story Section'), ('featured-grid', 'Secondary Featured Grid (3-4 stories)'), ('category-rail', 'Category Scroll Rail'), ('ad-slot', 'Advertisement Banner Block'), ('trending-widget', 'Trending & Popular List Sidebar'), ('news-desk', 'News Desk Section'), ('announcements', 'Amatangazo Classifieds Section'), ('lifestyle', 'Lifestyle & Culture Section'), ('sports-grid', 'Sports Vertical Grid Section'), ('featured-secondary', 'Second Featured Posts Row'), ('flyers', 'Local Partner Flyers Row'), ('you-missed', 'You Missed Scroll Rail'), ('rich-text', 'Custom Rich Text Block'), ('contact-form', 'Contact Inquiry Form')], max_length=30),
        ),
    ]
