# Generated by Django 6.0.7 on 2026-07-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='anonymous_identifier',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
