# Generated by Django 6.0.7 on 2026-07-13 16:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='Full announcement description or content')),
                ('announcement_type', models.CharField(choices=[('amasoko', 'Amasoko (Tenders)'), ('ibyemezo_by_urukiko', "Ibyemezo by'Urukiko (Court Decisions)"), ('akazi', 'Akazi (Jobs)'), ('guhindura_amazina', 'Guhindura Amazina (Name Change)'), ('other', 'Other')], max_length=30)),
                ('organization_name', models.CharField(help_text='e.g. QATAR CHARITY RWANDA, BPR Bank Rwanda Plc', max_length=255)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
                ('deadline_date', models.DateField(blank=True, help_text='Application or submission deadline', null=True)),
                ('attachment', models.FileField(blank=True, help_text='Optional PDF attachment', null=True, upload_to='announcements/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-published_date', '-id'],
            },
        ),
    ]
