# Generated by Django 6.0.7 on 2026-07-12 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('placement', models.CharField(choices=[('header-banner', 'Header Banner (970x250)'), ('sidebar-rail', 'Sidebar Rail (300x600)'), ('in-feed-native', 'In-Feed Native Ad Card'), ('in-article-inline', 'In-Article Inline (336x280)'), ('footer-banner', 'Footer Banner (728x90)'), ('interstitial', 'Interstitial Modal (Glass popup)')], max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/')),
                ('html_content', models.TextField(blank=True, help_text='For custom HTML/JS ad codes like Google Adsense')),
                ('target_url', models.URLField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher priority ads are served first')),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('pageview', 'Page View'), ('ad_impression', 'Ad Impression'), ('ad_click', 'Ad Click')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('referrer', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='ads.adslot')),
            ],
        ),
    ]
