# Generated by Django 6.0.7 on 2026-07-13 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adslot',
            name='cta_text',
            field=models.CharField(default='Learn More', max_length=50),
        ),
    ]
