# Generated by Django 6.0.7 on 2026-07-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_adslot_cta_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='adslot',
            name='sponsored_headline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='adslot',
            name='sponsored_logo',
            field=models.ImageField(blank=True, null=True, upload_to='ads/logos/'),
        ),
        migrations.AddField(
            model_name='adslot',
            name='sponsored_video_url',
            field=models.URLField(blank=True, help_text='For sponsored video embed block'),
        ),
        migrations.AlterField(
            model_name='adslot',
            name='placement',
            field=models.CharField(choices=[('header_banner', 'Header Banner (970x90 Leaderboard)'), ('hero_sidebar', 'Hero Sidebar (300x600 Skyscraper)'), ('daily_verse_sidebar', 'Daily Verse Sidebar (300x250 Medium Rectangle)'), ('news_desk_sidebar', 'News Desk Sidebar (300x600 Skyscraper)'), ('full_width_1', 'Full Width Banner 1 (728x90)'), ('full_width_2', 'Full Width Banner 2 (728x90)'), ('full_width_3', 'Full Width Banner 3 (728x90)'), ('full_width_4', 'Full Width Banner 4 (728x90)'), ('sponsored_content', 'Sponsored Content Block (Tax Corner style)'), ('grid_sidebar_stack_1', 'Grid Sidebar Stack Ad 1 (300x250)'), ('grid_sidebar_stack_2', 'Grid Sidebar Stack Ad 2 (300x250)'), ('grid_sidebar_stack_3', 'Grid Sidebar Stack Ad 3 (300x250)'), ('sports_sidebar', 'Sports Sidebar (300x600 Skyscraper)'), ('flyer_1', 'Flyer Ad 1 (Square/Portrait)'), ('flyer_2', 'Flyer Ad 2 (Square/Portrait)'), ('flyer_3', 'Flyer Ad 3 (Square/Portrait)'), ('header-banner', 'Legacy Header Banner (970x250)'), ('sidebar-rail', 'Legacy Sidebar Rail (300x600)'), ('in-feed-native', 'Legacy In-Feed Native Ad Card'), ('in-article-inline', 'Legacy In-Article Inline (336x280)'), ('footer-banner', 'Legacy Footer Banner (728x90)'), ('interstitial', 'Legacy Interstitial Modal (Glass popup)')], max_length=30),
        ),
    ]
